
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 27 17:27:43 CST 2017
//----------------------------------------------------

package iiproyecto;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int smbelse = 11;
  public static final int smbstruct = 26;
  public static final int smbamperson = 59;
  public static final int smbcircunflejoigual = 67;
  public static final int smbconst = 6;
  public static final int smbporcentajeigual = 65;
  public static final int smbdefault = 8;
  public static final int smbdiferente = 43;
  public static final int smbmayor = 39;
  public static final int smbigualigual = 37;
  public static final int smbfor = 15;
  public static final int smbmas = 48;
  public static final int smbint = 18;
  public static final int smbextern = 13;
  public static final int smbmultiplicacion = 50;
  public static final int smbmasmas = 35;
  public static final int smbdo = 9;
  public static final int smbcase = 4;
  public static final int smbfloat = 14;
  public static final int smbswitch = 27;
  public static final int smbtypedef = 28;
  public static final int smbreturn = 21;
  public static final int smbampersonigual = 66;
  public static final int smbcircunflejo = 60;
  public static final int smbmasigual = 55;
  public static final int smbcontinue = 7;
  public static final int smbunsigned = 30;
  public static final int smbauto = 2;
  public static final int smbwrite = 72;
  public static final int smbdivisionentera = 52;
  public static final int smbigual = 47;
  public static final int smbwhile = 33;
  public static final int smbunion = 29;
  public static final int smbvolatile = 32;
  public static final int smbrabocerdo = 64;
  public static final int smbor = 44;
  public static final int smbread = 71;
  public static final int smbfeclasderecha = 62;
  public static final int smbif = 17;
  public static final int smband = 45;
  public static final int smbmenorigual = 41;
  public static final int smbpregunta = 40;
  public static final int smbflechasizquierdaigual = 69;
  public static final int smbmenos = 49;
  public static final int smbmenor = 42;
  public static final int smbdospuntos = 53;
  public static final int smbbreak = 3;
  public static final int smbenum = 12;
  public static final int smbpunto = 54;
  public static final int smbdivision = 51;
  public static final int EOF = 0;
  public static final int smbflechasizquierda = 63;
  public static final int smbmenosigual = 56;
  public static final int smbstatic = 25;
  public static final int error = 1;
  public static final int smbgoto = 16;
  public static final int smbsigned = 23;
  public static final int smbadmiracion = 46;
  public static final int smbmenosmenos = 36;
  public static final int smbmayorigual = 38;
  public static final int smbcoma = 34;
  public static final int smbregister = 20;
  public static final int smbpipe = 61;
  public static final int smbfeclasderechaigual = 68;
  public static final int smbdouble = 10;
  public static final int smblong = 19;
  public static final int smbmultiplicacionigual = 57;
  public static final int smbsizeof = 24;
  public static final int smbdivisionigual = 58;
  public static final int smbchar = 5;
  public static final int smbshort = 22;
  public static final int smbvoid = 31;
  public static final int smbflecha = 70;
}

