
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 26 20:49:47 CST 2017
//----------------------------------------------------

package iiproyecto;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int error = 1;
  public static final int coma = 2;
  public static final int EOF = 0;
}

