
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 15 09:06:04 CST 2017
//----------------------------------------------------

package iiproyecto;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int smbvoid = 17;
  public static final int smbstring = 51;
  public static final int smbparentcerrar = 46;
  public static final int smbigual = 32;
  public static final int smbadmiracion = 29;
  public static final int smbelse = 9;
  public static final int smbdo = 8;
  public static final int smbdivisionigual = 41;
  public static final int smbread = 19;
  public static final int smbdec = 54;
  public static final int smbcharlit = 53;
  public static final int smbigualigual = 21;
  public static final int smbmasmas = 30;
  public static final int smbmenosigual = 39;
  public static final int smbdefault = 7;
  public static final int smblong = 13;
  public static final int smbmas = 33;
  public static final int smbmenos = 34;
  public static final int smbmenor = 25;
  public static final int smbbreak = 2;
  public static final int smboct = 56;
  public static final int smbmayor = 23;
  public static final int smbint = 12;
  public static final int smbhex = 55;
  public static final int smbchar = 4;
  public static final int EOF = 0;
  public static final int smbmenosmenos = 31;
  public static final int smbmultiplicacionigual = 40;
  public static final int smbor = 27;
  public static final int smbwhile = 18;
  public static final int smbfor = 10;
  public static final int smbdivision = 36;
  public static final int error = 1;
  public static final int smbdospuntos = 44;
  public static final int smbcase = 3;
  public static final int smband = 28;
  public static final int smbmultiplicacion = 35;
  public static final int smbllaveabrir = 49;
  public static final int smbif = 11;
  public static final int smbdivisionentera = 37;
  public static final int smbllavecerrar = 50;
  public static final int smbreturn = 14;
  public static final int smbdiferente = 26;
  public static final int smbmenorigual = 24;
  public static final int smbpuntocoma = 43;
  public static final int smbparentabrir = 45;
  public static final int smbcuadradocerrar = 48;
  public static final int smbshort = 15;
  public static final int smbcontinue = 6;
  public static final int smbswitch = 16;
  public static final int smbconst = 5;
  public static final int smbmayorigual = 22;
  public static final int smbidentificador = 52;
  public static final int smbcuadradoabrir = 47;
  public static final int smbcoma = 42;
  public static final int smbmasigual = 38;
  public static final int smbwrite = 20;
}

